// const fs = require("fs");
// console.log("process.env.NODE_ENV", process.env.NODE_ENV)
module.exports = {
    PORT: 8055,
    PUBLIC_URL: "http://localhost:8000",
    DB_CLIENT: "pg",
    DB_HOST: "localhost",
    DB_PORT: "5432",
    DB_DATABASE: "techkonsulter_prod",
    DB_USER: "postgres",
    DB_PASSWORD: "admin123",
    DB_SSL: "false",
    CORS_ENABLED: true,
    PASSWORD_RESET_URL_ALLOW_LIST:
        'array:http://localhost:3000/setpassword',
    CORS_ORIGIN: 'array:http://localhost:8000/items/AssetType,http://localhost:8000/items/Status_Codes,http://localhost:8000/items/Assets,http://localhost:8000/items/grade,http://localhost:8000/auth/login,https://productionv2.inspirepro.eu/items/Assets,https://productionv2.inspirepro.eu/items/grade,https://productionv2.inspirepro.eu/items/Pallets,https://productionv2.inspirepro.eu/roles,https://productionv2.inspirepro.eu/items/instructions,https://productionv2.inspirepro.eu/items/Certus,https://productionv2.inspirepro.eu/items/Pallets,http://localhost:8000/certus,https://productionv2.inspirepro.eu/items/Pallet_Column_Definitions,https://productionv2.inspirepro.eu/items/Pallets_Status_Codes,https://productionv2.inspirepro.eu/items/Status_Codes,https://productionv2.inspirepro.eu/items/User_Column_Definitions,https://productionv2.inspirepro.eu/items/Certus,https://productionv2.inspirepro.eu/items/CertusMobile,https://productionv2.inspirepro.eu/items/Certus_Column_Definitions,https://productionv2.inspirepro.eu/items/Certus_Mobile_Column_Definitions,https://productionv2.inspirepro.eu/items/users/ColumnDefinitions,https://productionv2.inspirepro.eu/items/users/roles,https://productionv2.inspirepro.eu/items/users,https://productionappv2.inspirepro.eu,https://productionv2.inspirepro.eu,https://productionappv2.inspirepro.eu/auth/login,https://productionv2.inspirepro.eu/auth/login,http://localhost:8000/auth/login,http://localhost:8000/items/Assets,http://localhost:8000/items/grade,http://localhost:8000/roles,http://localhost:8000/items/instructions,http://localhost:8000/items/Certus,http://localhost:8000/certus,http://localhost:8000/items/Pallet_Column_Definitions,http://localhost:8000/items/Pallets_Status_Codes,http://localhost:8000/items/Status_Codes,http://localhost:8000/items/User_Column_Definitions,http://localhost:8000/items/Certus,http://localhost:8000/items/CertusMobile,http://localhost:8000/items/Certus_Column_Definitions,http://localhost:8000/items/Certus_Mobile_Column_Definitions,http://localhost:8000/items/users/ColumnDefinitions,http://localhost:8000/items/users/roles,http://localhost:8000/items/users,https://productionappv2.inspirepro.eu,http://localhost:8000, http://localhost:8000, https://productionappv2.inspirepro.eu/auth/login,http://localhost:8000/auth/login,http://localhost:8000/auth/login,http://localhost:8000/items/Assets,http://localhost:8000/items/grade,http://localhost:8000/items/Pallets,http://localhost:8000/roles,http://localhost:8000/items/instructions,http://localhost:8000/items/Certus,http://localhost:8000/certus,http://localhost:8000/items/Pallet_Column_Definitions,http://localhost:8000/items/Pallets_Status_Codes,http://localhost:8000/items/Status_Codes,http://localhost:8000/items/User_Column_Definitions,http://localhost:8000/items/Certus,http://localhost:8000/items/CertusMobile,http://localhost:8000/items/Certus_Column_Definitions,http://localhost:8000/items/Certus_Mobile_Column_Definitions,http://localhost:8000/items/users/ColumnDefinitions,http://localhost:8000/items/users/roles,http://localhost:8000/items/users,https://productionappv2.inspirepro.eu,http://localhost:8000, http://localhost:8000, https://productionappv2.inspirepro.eu/auth/login,http://localhost:8000/auth/login,http://localhost:8000/auth/login',
    CORS_METHODS: 'GET,POST,PATCH,DELETE',
    CORS_ALLOWED_HEADERS: 'Content-Type,Authorization,X-Requested-With',
    CORS_EXPOSED_HEADERS: 'Content-Range',
    CORS_CREDENTIALS: 'true',
    CORS_MAX_AGE: 18000,
    RATE_LIMITER_ENABLED: false,
    RATE_LIMITER_STORE: "memory",
    RATE_LIMITER_POINTS: 25,
    RATE_LIMITER_DURATION: 1,
    CACHE_ENABLED: false,
    STORAGE_LOCATIONS: "local",
    STORAGE_LOCAL_DRIVER: "local",
    STORAGE_LOCAL_ROOT: "./uploads",
    KEY:"6507b425-f033-4f48-997f-ba3939e1d0d1",
    SECRET:"_bvJryyajtDyQDOaR2Ukqe5P5Ya-JKv_"  ,  
    ACCESS_TOKEN_TTL: "999d",
    REFRESH_TOKEN_TTL: "999d",
    REFRESH_TOKEN_COOKIE_SECURE: false,
    REFRESH_TOKEN_COOKIE_SAME_SITE: "lax",
    REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token",
    OAUTH_PROVIDERS: "",
    EXTENSIONS_PATH: "./extensions",
    EMAIL_FROM: "no-reply@directus.io",
    EMAIL_TRANSPORT: "sendmail",
    EMAIL_SENDMAIL_NEW_LINE: "unix",
    EMAIL_SENDMAIL_PATH: "/usr/sbin/sendmail",
    // etc
};